### ISSUE TITLE
Issue with search functionality for notes with '-' in title ?

### ISSUE THREAD

**Issue by agentcross** [lukaspustina/Evernote.lbaction#8] opened 2017-05-24 06:42 UTC
Hey, I think I found another little bug / limitation. I had a note with the title to-do. I could find it via your LaunchBar action but when I tried to open it always another note was opened. I checked the console which was not showing any error or exceptions messages. 

However, removing the '-' from the title did the trick and it is working again. 
Cheers,

**Comment by lukaspustina** [comment] 2017-05-25 18:37
I cannot reproduce the issue. Can you send me the note information as a screen shot like before?

**Comment by agentcross** [comment] 2017-05-28 09:56
It's somehow weird  because I cannot reproduce the issue either. 

When I tried to open the note 'to-do' the note 'ToDo heute' was opened. Please, find the note information below. 
![bildschirmfoto 2017-05-28 um 11 49 27](https://cloud.githubusercontent.com/assets/28731251/26527806/28ff0e42-439c-11e7-8b82-49ac63394d07.png)
![bildschirmfoto 2017-05-28 um 11 50 28](https://cloud.githubusercontent.com/assets/28731251/26527805/28dcaeec-439c-11e7-9bc0-efa1a42cac0c.png)

Once I renamed the note the problem was fixed... so I really don't know what caused the issue. In case, this should happen again, I will let you know.

**Comment by lukaspustina** [comment] 2017-05-28 11:14
Okay, maybe a glitch in the Matrix. I'm closing the issue but feel free to re-open it.

Meanwhile, I'm preparing a beta release for your "advanced" features. Stay tuned.

**Closed as completed by lukaspustina** 2017-05-28 11:14 UTC
Labels: invalid
